
#' Neu-InCoef.rda
#'
#' The clock's CpGs and coefficients.
#'
#' @docType data
#'
#' @usage data(Neu-InCoef)
#'
#' @keywords datasets
#'
#' @name clockCoef.df (from Neu-InCoef.rda)
#'
#' @format A data frame including 'coef', coefficients, and 'probe', CpGs
"clockCoef.df"

#' Neu-ExCoef.rda
#'
#' The clock's CpGs and coefficients.
#'
#' @docType data
#'
#' @usage data(Neu-ExCoef)
#'
#' @keywords datasets
#'
#' @name clockCoef.df (from Neu-ExCoef.rda)
#'
#' @format A data frame including 'coef', coefficients, and 'probe', CpGs
"clockCoef.df"

#' Glia-InCoef.rda
#'
#' The clock's CpGs and coefficients.
#'
#' @docType data
#'
#' @usage data(Glia-InCoef)
#'
#' @keywords datasets
#'
#' @name clockCoef.df (from Glia-InCoef.rda)
#'
#' @format A data frame including 'coef', coefficients, and 'probe', CpGs
"clockCoef.df"

#' Glia-ExCoef.rda
#'
#' The clock's CpGs and coefficients.
#'
#' @docType data
#'
#' @usage data(Glia-ExCoef)
#'
#' @keywords datasets
#'
#' @name clockCoef.df (from Glia-ExCoef.rda)
#'
#' @format A data frame including 'coef', coefficients, and 'probe', CpGs
"clockCoef.df"

#' BrainCoef.rda
#'
#' The clock's CpGs and coefficients.
#'
#' @docType data
#'
#' @usage data(BrainCoef)
#'
#' @keywords datasets
#'
#' @name clockCoef.df (from BrainCoef.rda)
#'
#' @format A data frame including 'coef', coefficients, and 'probe', CpGs.
"clockCoef.df"

#' HepClock.rda
#'
#' An object with S3 class generated by glmnet which include the
#' coefficients and CpGs of the clock.
#'
#' @docType data
#'
#' @usage data(HepClock)
#'
#' @keywords datasets
#'
#' @name HepClock.glm (from HepClock.rda)
#'
#' @format An object with S3 class generated by glmnet::glmnet().
"HepClock.glm"

#' LiverClock.rda
#'
#' An object with S3 class generated by glmnet which include the
#' coefficients and CpGs of the clock.
#'
#' @docType data
#'
#' @usage data(LiverClock)
#'
#' @keywords datasets
#'
#' @name LiverClock.glm (from LiverClock.rda)
#'
#' @format An object with S3 class generated by glmnet::glmnet().
"LiverClock.glm"

#' MurphyGSE88890.rda
#'
#' The example bulk prefrontal cortex (PFC) data is from Murphy et al. This is an
#' Illumina 450k dataset encompassing 38 normal PFC tissue samples and 37 PFC
#' major depressive disorder samples. Only controls are used here and only CTS
#' clock CpGs are in the data to control data size.
#'
#' @docType data
#'
#' @usage data(MurphyGSE88890)
#'
#' @keywords datasets
#'
#' @name beta.m (from MurphyGSE88890.rda)
#'
#' @format
#' A DNAm matrix. Row: CpGs, column: samples.
"beta.m"

#' MurphyGSE88890.rda
#'
#' The example bulk prefrontal cortex (PFC) data is from Murphy et al. This is an
#' Illumina 450k dataset encompassing 38 normal PFC tissue samples and 37 PFC
#' major depressive disorder samples. Only controls are used here and only CTS
#' clock CpGs and the necesarry deconvolution CpGs are in the data to control data size.
#'
#' @docType data
#'
#' @usage data(MurphyGSE88890)
#'
#' @keywords datasets
#'
#' @name beta.m (from MurphyGSE88890.rda)
#'
#' @format
#' A data frame including the chronological age.
"phenotype.df"

#' PaiGSE112179.rda
#'
#' The sorted PFC neuron data is from Pai et al. This is an Illumina EPIC dataset
#' encompassing 33 normal neuron tissue samples, 35 schizophrenia samples and
#' 32 bipolar disorder neuron samples. Only controls are used here and only CTS
#' clock CpGs and the necesarry deconvolution CpGs are in the data to control data size.
#'
#' @docType data
#'
#' @usage data(PaiGSE112179)
#'
#' @keywords datasets
#'
#' @name beta.m (from PaiGSE112179.rda)
#'
#' @format
#' A DNAm matrix. Row: CpGs, column: samples.
"beta.m"

#' PaiGSE112179.rda
#'
#' The sorted PFC neuron data is from Pai et al. This is an Illumina EPIC dataset
#' encompassing 33 normal neuron tissue samples, 35 schizophrenia samples and
#' 32 bipolar disorder neuron samples. Only controls are used here and only CTS
#' clock CpGs are in the data to control data size.
#'
#' @docType data
#'
#' @usage data(PaiGSE112179)
#'
#' @keywords datasets
#'
#' @name beta.m (from PaiGSE112179.rda)
#'
#' @format
#' A data frame including the chronological age.
"phenotype.df"

#' ExampleData_Liver.rda
#'
#' The sample liver data from GSE107038 contains 39 normal liver samples. Only
#' CTS clock CpGs are in the data to control data size.
#'
#' @docType data
#'
#' @usage data(ExampleData_Liver)
#'
#' @keywords datasets
#'
#' @name Test.m (from ExampleData_Liver.rda)
#'
#' @format
#' A DNAm matrix. Row: CpGs, column: samples.
"Test.m"

#' ExampleData_Liver.rda
#'
#' The sample liver data from GSE107038 contains 39 normal liver samples. Only
#' CTS clock CpGs are in the data to control data size.
#'
#' @docType data
#'
#' @usage data(ExampleData_Liver)
#'
#' @keywords datasets
#'
#' @name Age (from ExampleData_Liver.rda)
#'
#' @format
#' A vecter including the chronological age.
"Age"

